import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  manifest:"/manifest.json",
  title: "Create Next App",
  description: "Generated by create next app",
};

const viewport = {
  themeColor: "#FFFFFF"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Toaster />
      {children}</body>
    </html>
  );
}
